type: files
files:
  - usr: /usr
      # copies config/files/usr into your image's /usr.
  - etc: /etc
      # put configuration files you want in /etc/ on a booted system
      # in /usr/etc/ in the image. read more in files module reference.


