# image will be published to ghcr.io/<user>/<name>

name: ublue-kde-workstation
#name: ublue-blaze
# description will be included in the image's metadata
description: This is my personal OS KDE image with additionnal applications installed.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP; rawhide is unavailable

# module configuration, executed in order
# you can include multiple instances of the same module

# Files
modules:
  - from-file: files/files.yml

# Install rpm-ostree packages
modules:
  - from-file: common_modules/rpm-ostree/backup.yml
  - from-file: common_modules/rpm-ostree/base.yml
  - from-file: common_modules/rpm-ostree/hardware.yml
  - from-file: common_modules/rpm-ostree/kde.yml
  - from-file: common_modules/rpm-ostree/language.yml
  - from-file: common_modules/rpm-ostree/laptop.yml
  - from-file: common_modules/rpm-ostree/multimedia.yml
  - from-file: common_modules/rpm-ostree/printer.yml
  - from-file: common_modules/rpm-ostree/syncthing.yml
  - from-file: common_modules/rpm-ostree/terminal.yml
  - from-file: common_modules/rpm-ostree/virtualization.yml
  - from-file: common_modules/rpm-ostree/web.yml

# Flatpack:
modules:
  - from-file: flatpak/install.yml
  - from-file: flatpak/remove.yml

# Systemd
modules:
  - from-file: systemd/rpm-ostree-countme.yml # Disable RedHat countme telemetry
  - from-file: systemd/rpm-ostree-boot-check.yml # Run a script on boot
  - from-file: systemd/rpm-ostreed-deployed.yml # Run a script on rpm-ostree rebase/upgrade
  - from-file: systemd/rpm-ostreed-firstboot.yml # Run a script on first boot after fresh install
  - from-file: systemd/sshd.yml # Enable sshd

# Scripts
modules:
  - from-file: scripts/scripts.yml
  #- from-file: scripts/snippets.yml

# Chezmoi
#modules:
#  - from-file: chezmoi/chezmoi.yml # Enable and run chezmoi to set dotfiles

# Fonts
modules:
  - from-file: fonts/fonts.yml

modules:
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
