# image will be published to ghcr.io/<user>/<name>
name: ublue-kde-workstation
# description will be included in the image's metadata
description: This is my personal OS KDE image with additionnal applications installed.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP; rawhide is unavailable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.
          # Build skel to fetch dotfiles

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # BASE
        - ansible
        - aria2
        - btop
        - colordiff
        - curl
        - dfc
        - expect
        - git
        - htop
        - inxi
        - less
        - lm_sensors
        - lsof
        - man
        - neofetch
        - neovim
        - net-tools
        - nmon
        - pv
        - screen
        - tmux
        - wget
      # COMPRESSION
        - p7zip
        - unrar
        - unzip
      # Iphone and android
        - ifuse
        - libimobiledevice-utils
        #- nautilus
        #- nautilus-gsconnect
        - usbmuxd
      # ENCRYPTION
        - pass
        - qtpass
      # KDE
        - kate
        #- kdenlive
        - kompare
        - krdc
        - krfb
        - qownnotes
        - yakuake
      # LANGUAGE
        - langpacks-en
        - langpacks-fr
      # GAMING
        - steam-devices
      # DEVICES
        - printer-driver-brlaser
      # MULTIMEDIA
        - yt-dlp
        - yt-dlp-bash-completion
      # UTILS
        - borgbackup
        - borgmatic
        - syncthing
      # VIRTUALIZATION
        - akmod-v4l2loopback #for podman_ff
        - distrobox
        - guestfs-tools
        - libvirt-daemon-config-network
        - libvirt-daemon-kvm
        - podman
        - python3-libguestfs
        - qemu-kvm
        - toolbox
        - virt-install
        - virt-manager
        - virt-top
        - virt-viewer

    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # NETWORK
        - org.mozilla.firefox
        - com.github.Eloston.UngoogledChromium
        - io.gitlab.librewolf-community
        - org.netsurf_browser.NetSurf
        - org.torproject.torbrowser-launcher
        - org.mozilla.Thunderbird
        - xyz.ketok.Speedtest
        - io.github.bytezz.IPLookup
        # VIDEO
        - org.videolan.VLC
        #- com.obsproject.Studio
        #- org.kde.kdenlive
        #- fr.handbrake.ghb
        #- tv.kodi.Kodi
        - com.warlordsoftwares.youtube-downloader-4ktube
        - fr.nytuo.cosmiccomics
        # UTILS
        - com.github.tchx84.Flatseal
        #- io.github.thetumultuousunicornofdarkness.cpu-x
        # GAMES
        - com.valvesoftware.Steam
        # EMULATORS
        #- org.DolphinEmu.dolphin-emu #Gamecube EMU
        #- org.ppsspp.PPSSPP
        #- net.rpcs3.RPCS3 # PS3 EMU
        #- org.duckstation.DuckStation
        #- org.scummvm.ScummVM
        # OFFICE
        - org.libreoffice.LibreOffice
        - org.gnu.emacs
        - org.gimp.GIMP
        - org.kde.kdenlive
        # JOB
        - com.github.IsmaelMartinez.teams_for_linux
      remove:
        # - org.gnome.eog
        #- plasma-discover
        #- plasma-discover-notifier
        #- plasma-discover-rpm-ostree

  - type: systemd
    system:
      #enabled:
        #- on_boot.service
        #- rc-local.service
        - sshd.service
      disabled:
        - rpm-ostree-countme.timer # RedHat telemetry disabling  
        - rpm-ostree-countme.service
        #- sshd.service
      #masked:
      #  - rpm-ostree-countme.service
      #  - rpm-ostree-countme.timer
      unmasked:
        - rpm-ostree-countme.service
        - rpm-ostree-countme.timer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
