
# Install base packages that provide complete terminal functions without jumping right in a distrobox

type: rpm-ostree
  install:
    - ansible
    - aria2
    - bat
    - bc
    - bind-utils
    - btop
    - colordiff
    - curl
    - dfc
    - dua-cli
    - duf
    - expect
    - eza
    - fd-find
    - fish
    - fontconfig
    - fzf
    - git
    - git-delta
    - gitui
    - gnupg
    - gopass
    - htop
    - inxi
    - jq
    - less
    - lm_sensors
    - lsof
    - man
    - mc
    - neofetch
    - neovim
    - net-tools
    - nmon
    - p7zip
    - p7zip-plugins
    - procs
    - psmisc
    - pv
    - python3-pip
    - ripgrep
    - rng-tools
    - rsync
    - screen
    - smartmontools
    - stow
    - tar
    - tldr
    - tmux
    - tree
    - unrar
    - unzip
    - wget
    - wl-clipboard
    - zoxide
    - zstd

