
# Install base packages that provide minimal terminal functions 

type: rpm-ostree
install:
  - aria2
  - bind-utils
  - curl
  - less
  - lsof
  - net-tools
  - nmon
  - pv
  - rsync
  - screen
  - stow
  - tar
  - tree
  - unzip
  - wget
  - zstd
remove:
  - plasma-discover-notifier

